export const ADD_STERN_STORE = 'ADD_STERN_STORE'
export const REMOVE_STERN_STORE = 'REMOVE_STERN_STORE'
export const RESET_STORE_STATE = 'RESET_STORE_STATE'
export const ADD_STERN_PARAMS = 'ADD_STERN_PARAMS'